export const SET_TITLE_HEADER_APP = 'SET_TITLE_HEADER_APP'

export const INITIAL_USER_STATE = 'INITIAL_USER_STATE'
export const POST_USER_REQUEST = 'POST_USER_REQUEST'
export const POST_USER_SUCCESS = 'POST_USER_SUCCESS'
export const POST_USER_ERROR = 'POST_USER_ERROR'
export const FINALLY_USER_REGISTER = 'FINALLY_USER_REGISTER'

export const INITIAL_EVENT_STATE = 'INITIAL_EVENT_STATE'
export const POST_EVENT_REQUEST = 'POST_EVENT_REQUEST'
export const POST_EVENT_SUCCESS = 'POST_EVENT_SUCCESS'
export const POST_EVENT_ERROR = 'POST_EVENT_ERROR'
export const FINALLY_EVENT_REGISTER = 'FINALLY_EVENT_REGISTER'

